// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import static org.junit.Assert.*;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;

import java.time.Duration;
import java.util.*;
public class Avia {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        driver.manage().window().maximize();
        vars = new HashMap<String, Object>();
    }

    public String waitForWindow(int timeout) {
        try {
            Thread.sleep(timeout);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        Set<String> whNow = driver.getWindowHandles();
        Set<String> whThen = (Set<String>) vars.get("window_handles");
        if (whNow.size() > whThen.size()) {
            whNow.removeAll(whThen);
        }
        return whNow.iterator().next();
    }


    @Test
    public void test() {
        driver.get("https://www.tinkoff.ru/travel/");
        String fromXPath = "/html/body/div[1]/div/div/div[5]/div/div/form/div[1]/div[3]/div/div[2]/div/div[2]/div[1]/div/div[1]/table/tbody/tr[5]/td[1]";
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
        wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".travelsearchform__cNaJW7 > div:nth-child(2) > div:nth-child(1) > input:nth-child(2)"))).sendKeys("Москва");
        wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[1]/div/div/div[5]/div/div/form/div[1]/div[3]/div/div/div[2]/div/div/div/div/div[2]/div[2]"))).click();


        wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath(fromXPath))).click();
        wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[1]/div/div/div[5]/div/div/form/div[1]/div[3]/div/div[2]/div/div[2]/div[1]/div/div[1]/table/tbody/tr[5]/td[7]"))).click();
        vars.put("window_handles", driver.getWindowHandles());
        driver.findElement(By.xpath("/html/body/div[1]/div/div/div[5]/div/div/form/div[2]/div[2]/button/span")).click();
        vars.put("win7796", waitForWindow(6000));
        driver.switchTo().window(vars.get("win7796").toString());
//        js.executeScript("arguments[0].scrollIntoView(false);", driver.findElement(By.xpath("/html/body/div[1]/div/div/div[3]/div[2]/div[3]/div/div/div[1]/div/div[2]/div[1]/div/div/div/div")));
        wait.until(ExpectedConditions.stalenessOf(driver.findElement(By.xpath("/html/body/div[1]/div/div/div[3]/div[2]/div[3]/div/div/div[1]/div/div[2]/div[1]/div/div/div"))));
        driver.findElement(By.xpath("/html/body/div[1]/div/div/div[3]/div[2]/div[3]/div/div/div[1]/div/div[2]/div[1]/div/div/div")).click();
        driver.findElement(By.xpath("/html/body/div[1]/div/div/div[3]/div[2]/div[3]/div/div/div[2]/div/div[2]/div[1]/div/div/div")).click();
        driver.findElement(By.xpath("/html/body/div[4]/div[3]/div/div[2]/div/div/div/div[2]/div/div/div/div[2]/div/div[3]/button/span")).click();

        wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[1]/div/div/div[3]/div/div[3]/div/div[1]/div/div[2]/div/div[1]/div[1]")));
        assertEquals("Санкт-Петербург — Москва", js.executeScript("return document.evaluate(\"/html/body/div[1]/div/div/div[3]/div/div[3]/div/div[1]/div/div[2]/div/div[1]/div[1]/div[1]/div/div[1]/div[2]\", document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue.innerHTML").toString());
        assertEquals("24 апреля", js.executeScript("return document.evaluate(\"/html/body/div[1]/div/div/div[3]/div/div[3]/div/div[1]/div/div[2]/div/div[1]/div[1]/div[2]/div/div/div/div/div[3]/div[1]/div/div[2]/div\", document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue.innerHTML").toString());

        assertEquals("Москва — Санкт-Петербург", js.executeScript("return document.evaluate(\"/html/body/div[1]/div/div/div[3]/div/div[3]/div/div[1]/div/div[2]/div/div[1]/div[2]/div[1]/div/div[1]/div[2]\", document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue.innerHTML").toString());
        assertEquals("30 апреля", js.executeScript("return document.evaluate(\"/html/body/div[1]/div/div/div[3]/div/div[3]/div/div[1]/div/div[2]/div/div[1]/div[2]/div[2]/div/div/div/div/div[3]/div[1]/div/div[2]/div\", document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue.innerHTML").toString());
    }
}