// Generated by Selenium IDE
import org.junit.After;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;

import java.time.Duration;
import java.util.*;
public class Avia {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    public String waitForWindow(int timeout) {
        try {
            Thread.sleep(timeout);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        Set<String> whNow = driver.getWindowHandles();
        Set<String> whThen = (Set<String>) vars.get("window_handles");
        if (whNow.size() > whThen.size()) {
            whNow.removeAll(whThen);
        }
        return whNow.iterator().next();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void testChrome(){
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
        test();
    }

    @Test
    public void testFirefox(){
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
        test();
    }
    
    private void test() {
        driver.get("https://www.tinkoff.ru/travel/");
        String fromXPath = "/html/body/div[1]/div/div/div[5]/div/div/form/div[1]/div[3]/div/div[2]/div/div[2]/div[1]/div/div[1]/table/tbody/tr[5]/td[1]";
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
        wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".travelsearchform__cNaJW7 > div:nth-child(2) > div:nth-child(1) > input:nth-child(2)"))).sendKeys("Москва");
        wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[1]/div/div/div[5]/div/div/form/div[1]/div[3]/div/div/div[2]/div/div/div/div/div[2]/div[2]"))).click();
        
        wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath(fromXPath))).click();
        wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[1]/div/div/div[5]/div/div/form/div[1]/div[3]/div/div[2]/div/div[2]/div[1]/div/div[1]/table/tbody/tr[5]/td[7]"))).click();
    }
}