// Generated by Selenium IDE
import org.junit.Assert;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.time.Duration;
import java.util.*;

public class PopularAviaCompaniesTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    private WebDriverWait wait;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
        wait = new WebDriverWait(driver, Duration.ofSeconds(10));
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    public String waitForWindow(int timeout) {
        try {
            Thread.sleep(timeout);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        Set<String> whNow = driver.getWindowHandles();
        Set<String> whThen = (Set<String>) vars.get("window_handles");
        if (whNow.size() > whThen.size()) {
            whNow.removeAll(whThen);
        }
        return whNow.iterator().next();
    }
    @Test
    public void testPopularAviaCompanies() {
        driver.get("https://www.tinkoff.ru/travel/flights");
        driver.manage().window().setSize(new Dimension(1552, 840));
        wait.until(ExpectedConditions.presenceOfElementLocated(
                By.xpath("//section/div/h2"))
        );
        // Проверяем количество показанных авиакомпаний
        var routesNumber = driver.findElements(By.className("AirlineItem__airline_BH941")).size();
        Assert.assertEquals(9, routesNumber);

        // Проверяем наличие авиакомпании Победа
        var found = driver
                .findElements(By.className("AirlineItem__airline_BH941"))
                .stream()
                .anyMatch(el -> el.getText().equals("Победа"));
        Assert.assertTrue(found);

        driver.findElements(By.className("AirlineItem__name_sIpiM"))
                .stream()
                .filter(el -> el.getText().equals("Победа"))
                .findFirst()
                .get()
                .click();
        var title = wait.until(ExpectedConditions.presenceOfElementLocated(
                By.xpath("//p"))
        ).getText();
        Assert.assertEquals(
                "Поиск билетов авиакомпании Победа",
                title
        );
    }
}