// Generated by Selenium IDE
import org.junit.Assert;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.time.Duration;
import java.util.*;
import java.util.regex.Pattern;

public class PopularDestinationsTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    private WebDriverWait wait;
    JavascriptExecutor js;
    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void testChrome(){
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
        wait = new WebDriverWait(driver, Duration.ofSeconds(10));
        testPopularDestinations();
    }

    @Test
    public void testFirefox(){
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
        wait = new WebDriverWait(driver, Duration.ofSeconds(10));
        testPopularDestinations();
    }
    public String waitForWindow(int timeout) {
        try {
            Thread.sleep(timeout);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        Set<String> whNow = driver.getWindowHandles();
        Set<String> whThen = (Set<String>) vars.get("window_handles");
        if (whNow.size() > whThen.size()) {
            whNow.removeAll(whThen);
        }
        return whNow.iterator().next();
    }
    private void testPopularDestinations() {
        driver.get("https://www.tinkoff.ru/travel/flights");
        driver.manage().window().setSize(new Dimension(1552, 840));
        wait.until(ExpectedConditions.presenceOfElementLocated(
                By.xpath("//div[12]/div/div/div/div"))
        );
        // Проверяем количество показанных направлений
        var routesNumber = driver.findElements(By.className("styles__route_D71Hr")).size();
        Assert.assertEquals(12, routesNumber);

        // Проверяем наличие направления СПб - Москва
        var found = (Boolean) js.executeScript("""
                return !!Array.from(document.querySelectorAll('.Link-module__inner_AUi26'))
                    .map(el => el.innerText)
                    .find(text => text === "Санкт-Петербург — Москва")""");
        Assert.assertTrue(found);
        
        driver.findElement(By.xpath("//span[contains(.,'Москва — Санкт-Петербург')]")).click();
        Assert.assertTrue(
                Pattern.matches("\\S*MOW/LED\\S*", driver.getCurrentUrl())
        );
    }
}