//// Generated by Selenium IDE
//import org.junit.Test;
//import org.junit.Before;
//import org.junit.After;
//import static org.junit.Assert.*;
//import static org.hamcrest.CoreMatchers.is;
//import static org.hamcrest.core.IsNot.not;
//import org.openqa.selenium.By;
//import org.openqa.selenium.WebDriver;
//import org.openqa.selenium.firefox.FirefoxDriver;
//import org.openqa.selenium.chrome.ChromeDriver;
//import org.openqa.selenium.remote.RemoteWebDriver;
//import org.openqa.selenium.remote.DesiredCapabilities;
//import org.openqa.selenium.Dimension;
//import org.openqa.selenium.WebElement;
//import org.openqa.selenium.interactions.Actions;
//import org.openqa.selenium.support.ui.ExpectedConditions;
//import org.openqa.selenium.support.ui.WebDriverWait;
//import org.openqa.selenium.JavascriptExecutor;
//import org.openqa.selenium.Alert;
//import org.openqa.selenium.Keys;
//
//import java.time.Duration;
//import java.util.*;
//import java.net.MalformedURLException;
//import java.net.URL;
//public class SignInTest {
//  private WebDriver driver;
//  private Map<String, Object> vars;
//  JavascriptExecutor js;
//  @Before
//  public void setUp() {
//    driver = new ChromeDriver();
//    driver.manage().window().maximize();
//    js = (JavascriptExecutor) driver;
//    vars = new HashMap<String, Object>();
//  }
//  @After
//  public void tearDown() {
//    driver.quit();
//  }
//  @Test
//  public void signIn() {
//    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
//    // Test name: Sign In
//    // Step # | name | target | value | comment
//    // 1 | open | https://www.tinkoff.ru/travel/ |  |
//    driver.get("https://www.tinkoff.ru/travel/");
//    // 2 | setWindowSize | 1551x832 |  |
//    // 4 | executeScript | return (document.evaluate("/html/body/div[1]/div/div/header/div/div/div/div/div/div[3]/div/div[1]/nav/span/a/span", document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue == null) | user_button |
//    vars.put("user_button", js.executeScript("return (document.evaluate(\"/html/body/div[1]/div/div/header/div/div/div/div/div/div[3]/div/div[1]/nav/span/a/span\", document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue == null)"));
//    // 5 | echo | ${user_button} |  |
//    System.out.println(vars.get("user_button").toString());
//    // 6 | if | ${user_button} == false |  |
//    if ((Boolean) js.executeScript("return (arguments[0] == false)", vars.get("user_button"))) {
//      // 7 | click | css=.header__eFb1M2 path |  |
//      driver.findElement(By.cssSelector(".header__eFb1M2 path")).click();
//      // 8 | click | css=.header__cc5zQh |  |
//      driver.findElement(By.cssSelector(".header__cc5zQh")).click();
//      // 9 | open | https://www.tinkoff.ru/travel/ |  |
//      driver.get("https://www.tinkoff.ru/travel/");
//      // 10 | end |  |  |
//    }
//    // 11 | click | css=.header__b6rNeQ |  |
//    driver.findElement(By.cssSelector(".header__b6rNeQ")).click();
//    // 12 | type | id=password | ПАРОЛЬ |
//    wait.until(ExpectedConditions.presenceOfElementLocated(By.id("password"))).sendKeys("nnik1320pelmen13201320TnKfF!");
//    // 13 | click | xpath=//button[@id='submit-button'] |  |
//    driver.findElement(By.xpath("//button[@id=\'submit-button\']")).click();
//    // 14 | click | css=.header__eFb1M2 path |  |
//    driver.findElement(By.cssSelector(".header__eFb1M2 path")).click();
//    // 15 | assertText | xpath=//div[6]/div/div/div/div/div/span | Никита Кошкарбаев |
//    assertThat(driver.findElement(By.xpath("//div[6]/div/div/div/div/div/span")).getText(), is("Никита Кошкарбаев"));
//  }
//}
