// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.security.Key;
import java.time.Duration;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Tour {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    driver.manage().window().maximize();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(3));
  }


  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }

  @Test
  public void test() {
    // Test name: Выбор тура
    // Step # | name | target | value | comment
    // 1 | open | https://tinkoff.travelata.ru/search#?fromCity=1&toCountry=92&toCity=2162&dateFrom=09.05.2023&dateTo=09.05.2023&nightFrom=2&nightTo=7&adults=1&hotelClass=all&meal=all&priceFrom=6000&priceTo=50000000&sid=soe88ysxj5&sort=recommend |  | 
    driver.get("https://tinkoff.travelata.ru/search#?fromCity=1&toCountry=92&toCity=2162&dateFrom=09.05.2023&dateTo=09.05.2023&nightFrom=2&nightTo=7&adults=1&hotelClass=all&meal=all&priceFrom=6000&priceTo=50000000&sid=soe88ysxj5&sort=recommend");
    // 2 | setWindowSize | 1303x702 |  | 

    // 3 | waitForElementVisible | xpath=(//input[@type='text'])[5] | 30000 | 
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("(//input[@type='text'])[5]")));
    }
    // 4 | click | xpath=//div[@id='forSearchView']/div[4]/div/div[7]/div/div[5]/div/div |  | 
    driver.findElement(By.xpath("//div[@id='forSearchView']/div[4]/div/div[7]/div/div[5]/div/div")).click();
    // 5 | type | xpath=(//input[@type='text'])[5] | 150 000 |
    driver.findElement(By.xpath("(//input[@type='text'])[5]")).sendKeys(Keys.CONTROL + "a");
    driver.findElement(By.xpath("(//input[@type='text'])[5]")).sendKeys(Keys.DELETE);
    driver.findElement(By.xpath("(//input[@type='text'])[5]")).sendKeys("150 000");
    // 6 | sendKeys | xpath=(//input[@type='text'])[5] | ${KEY_ENTER} |
    driver.findElement(By.xpath("(//input[@type='text'])[5]")).sendKeys(Keys.ENTER);
    // 7 | click | xpath=//div[@id='forSearchView']/div[4]/div/div[7]/div/div[6]/ul/li[2]/div/label/div |  |
    driver.findElement(By.xpath("//div[@id='forSearchView']/div[4]/div/div[7]/div/div[6]/ul/li[2]/div/label/div")).click();
    // 8 | click | xpath=//div[@id='forSearchView']/div[4]/div/div[7]/div/div[6]/ul/li[3]/div/label/div |  |
    driver.findElement(By.xpath("//div[@id='forSearchView']/div[4]/div/div[7]/div/div[6]/ul/li[3]/div/label/div")).click();
    // 9 | click | xpath=//div[@id='forSearchView']/div[4]/div/div[7]/div/div[8]/div/ul/li/div/label/div |  |
    driver.findElement(By.xpath("//div[@id='forSearchView']/div[4]/div/div[7]/div/div[8]/div/ul/li/div/label/div")).click();
    // 10 | waitForElementPresent | xpath=//div[@id='hotelTemplate']/div[1]/div | 30000 |

    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
    wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//div[@id=\'hotelTemplate\']/div[1]/div")));

    // 11 | executeScript | return document.evaluate("//div[@id='hotelTemplate']/div[1]/div/div[2]/div/div[2]/div/div", document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue.childElementCount | random_tour_stars |
    vars.put("random_tour_stars", js.executeScript("return document.evaluate(\"//div[@id=\'hotelTemplate\']/div[1]/div/div[2]/div/div[2]/div/div\", document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue.childElementCount"));
    // 12 | echo | ${random_tour_stars} |  |
    System.out.println(vars.get("random_tour_stars").toString());
    // 13 | if | ${random_tour_stars} == 4 |  |
    if ((Boolean) js.executeScript("return (arguments[0] == 4)", vars.get("random_tour_stars"))) {
      // 15 | else |  |  |
    } else {
      // 16 | assert | random_tour_stars | 5 |
      assertEquals(vars.get("random_tour_stars").toString(), "5");
      // 17 | end |  |  |
    }
    // 18 | click | xpath=//div[@id='forSearchView']/div[4]/div/div[6]/div[2]/div[2]/span |  |
    js.executeScript("arguments[0].scrollIntoView(false);", driver.findElement(By.xpath("//div[@id='forSearchView']/div[4]/div/div[6]/div[2]/div[2]/span")));
    driver.findElement(By.xpath("//div[@id='forSearchView']/div[4]/div/div[6]/div[2]/div[2]/span")).click();
    // 19 | click | xpath=//div[@id='forSearchView']/div[4]/div/div[6]/div[2]/div[3]/span |  |
    driver.findElement(By.xpath("//div[@id=\'forSearchView\']/div[4]/div/div[6]/div[2]/div[3]/span")).click();
    // 20 | executeScript | return document.evaluate("//div[@id='hotelTemplate']/div/div/div[2]/div[2]/a/span/span", document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue.innerHTML > '150 000' | check_price |
    vars.put("check_price", js.executeScript("return document.evaluate(\"//div[@id=\'hotelTemplate\']/div/div/div[2]/div[2]/a/span/span\", document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue.innerHTML > \'150 000\'"));
    // 21 | echo | ${check_price} |  |
    System.out.println(vars.get("check_price").toString());
    // 22 | assert | check_price | false |
    assertEquals(vars.get("check_price").toString(), "false");
    // 23 | waitForElementPresent | xpath=//div[@id='hotelTemplate']/div/div/div[2]/div[2]/a | 30000 |

    wait = new WebDriverWait(driver, Duration.ofSeconds(30));
    wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//div[@id=\'hotelTemplate\']/div/div/div[2]/div[2]/a")));

    //24 | click | xpath=//div[@id='hotelTemplate']/div/div/div[2]/div[2]/a |  |
    vars.put("window_handles", driver.getWindowHandles());
    // 25 | selectWindow | handle=${win7796} |  |
    js.executeScript("arguments[0].scrollIntoView(false);", driver.findElement(By.xpath("//div[@id='hotelTemplate']/div/div/div[2]/div[2]/a")));
    wait.until(ExpectedConditions.stalenessOf(driver.findElement(By.xpath("//div[@id='hotelTemplate']/div/div/div[2]/div[2]/a"))));
    vars.put("name_of_tour", js.executeScript("return document.evaluate(\"//*[@id=\\\"hotelTemplate\\\"]/div[1]/div[1]/div[2]/div[1]/div[2]/div/a/text()\", document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue.wholeText"));
    driver.findElement(By.xpath("//div[@id='hotelTemplate']/div/div/div[2]/div[2]/a")).click();
    vars.put("win7796", waitForWindow(6000));
    driver.switchTo().window(vars.get("win7796").toString());
    vars.put("name_of_tour2", js.executeScript("return document.evaluate(\"/html/body/section/div/div/div/section[1]/div/div/div[2]/div[1]/div[1]/div[3]/text()\", document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue.wholeText"));
    assertEquals(vars.get("name_of_tour").toString(), vars.get("name_of_tour2").toString().substring(0, vars.get("name_of_tour2").toString().length() - 1));
  }
}
