// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.time.Duration;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Travelata {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new ChromeDriver();
        driver.manage().window().maximize();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @Test
    public void test() throws InterruptedException {
        driver.get("https://tinkoff.travelata.ru/search#?fromCity=1&toCountry=92&toCity=2162&dateFrom=09.05.2023&dateTo=09.05.2023&nightFrom=2&nightTo=7&adults=1&hotelClass=all&meal=all&priceFrom=6000&priceTo=50000000&sid=5me00sj2qs&sort=recommend");
        vars.put("counts", driver.findElements(By.xpath("//span[contains(.,\'Войти в Личный кабинет\')]")).size());
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
        if ((Boolean) js.executeScript("return (arguments[0] > 0)", vars.get("counts"))) {
            wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//span[contains(.,\'Войти в Личный кабинет\')]")));
            driver.findElement(By.xpath("//span[contains(.,\'Войти в Личный кабинет\')]")).click();
            wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//input[@id=\'accountAuthorize__email\']")));
            driver.findElement(By.xpath("//input[@id=\'accountAuthorize__email\']")).click();
            driver.findElement(By.xpath("//input[@id=\'accountAuthorize__email\']")).sendKeys("nik231002@mail.ru");
            driver.findElement(By.xpath("//input[@id=\'accountAuthorize__email\']")).sendKeys(Keys.ENTER);
            driver.findElement(By.xpath("//input[@id=\'accountAuthorize__password\']")).click();
            driver.findElement(By.xpath("//input[@id=\'accountAuthorize__password\']")).sendKeys("Nnik1320");
            driver.findElement(By.xpath("//input[@id=\'accountAuthorize__password\']")).sendKeys(Keys.ENTER);
           Thread.sleep(2000);
            assertThat(driver.findElement(By.xpath("//div[@id=\'accountBar\']/div/span")).getText(), is("nik231002@mail.ru"));
        }
    }
}
